# Generated by Django 4.1.2 on 2022-10-10 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=320)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(default="", max_length=50)),
                ("password", models.CharField(max_length=50)),
                (
                    "role",
                    models.CharField(
                        choices=[("I", "Interviwer"), ("C", "Candidate")],
                        default="C",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Interviews",
            fields=[
                ("interview_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("C", "Completed"), ("P", "Pending")],
                        default="P",
                        max_length=2,
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="InterviewFix.users",
                    ),
                ),
            ],
        ),
    ]
