# Generated by Django 4.1.2 on 2022-10-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("InterviewFix", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="interviews", old_name="user_id", new_name="user",
        ),
        migrations.AlterField(
            model_name="users",
            name="last_name",
            field=models.CharField(default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="role",
            field=models.CharField(
                choices=[("I", "Interviewer"), ("C", "Candidate")],
                default="C",
                max_length=2,
            ),
        ),
    ]
