# Generated by Django 4.1.2 on 2022-10-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "InterviewFix",
            "0002_rename_user_id_interviews_user_alter_users_last_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="interviews", name="date",),
        migrations.AlterField(
            model_name="interviews", name="end_time", field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="interviews", name="start_time", field=models.DateTimeField(),
        ),
    ]
