# Generated by Django 4.1.2 on 2022-10-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "InterviewFix",
            "0003_remove_interviews_date_alter_interviews_end_time_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(old_name="Interviews", new_name="Interview",),
        migrations.RenameModel(old_name="Users", new_name="User",),
    ]
